export { CourseHeader } from './CourseHeader'
export { GeneralInfoTab } from './GeneralInfoTab'
export { SyllabusTab } from './SyllabusTab'
export { SlidePreviewModal } from './SlidePreviewModal'
export type { CourseData } from './types'
